account/urls.py
from django.urls import path
from . views import login_view, signup_view, logout_view

app_name = 'account'
urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout')

]

article/urls.py
from django.urls import path
from . views import create_article, delete_article, update_article, article_list, detailed_article

app_name = 'article'
urlpatterns = [
    path('create/', create_article, name='create'),
    path('delete/', delete_article, name='delete'),
    path('update/', update_article, name='update'),
    path('detail/<title>',detailed_article, name='detail')

]

comment/urls.py
from django.urls import path
from . views import create_comment, delete_comment, update_comment
app_name = 'comment'
urlpatterns = [
    path('create/', create_comment, name='create'),
    path('delete/', delete_comment, name='delete'),
    path('update/', update_comment, name='update'),
]

disQus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from article import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.article_list, name='home'),
    path('about', TemplateView.as_view(template_name='about.html'), name='about'),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('comment/', include('comment.urls')),
    path('base', TemplateView.as_view(template_name='base.html'), name='base')

]

account/models.py
from django.db import models

# Create your models here.

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    slug = models.SlugField()
    publish_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

comment/models.py
from django.db import models
from article.models import Article
from django.contrib.auth.models import User
# Create your models here.

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, default=None)
    owner = models.ForeignKey(User, on_delete=models.CASCADE,default=None)
    answer = models.TextField()
    published_at = models.DateTimeField(auto_now_add=True, blank=True)

article/forms.py
from . models import Article
from django import forms


class ArticleCreationForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'description', 'slug')

comment/forms.py
from django import forms
from . models import Comment
class CommentCreationForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('answer',)

account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import  login, logout
# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            print(type(user))
            return HttpResponseRedirect(reverse('home'))
    else:
        form = UserCreationForm()

    context = {
        'form':form
    }
    return render(request, 'account/signup.html',context)


def login_view(request):
    if request.method == 'POST':
        print(request)
        print(request.POST)
        print(type(request.POST))
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            print('----------------next Url-----------------')
            print(request.POST.get('next'))
            if request.POST.get('next') :
                return redirect(request.POST['next'])
            return HttpResponseRedirect(reverse('home'))
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'account/login.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

article/views.py
from django.shortcuts import render, redirect
from .forms import ArticleCreationForm
from django.contrib.auth.decorators import login_required

import comment.models as cModels
import comment.forms as  cForms

from .models import Article
# Create your views here.
from django.contrib.auth.models import User

@login_required(login_url='account/login')
def create_article(request):
    if request.method == 'POST':
        form = ArticleCreationForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
        return redirect('home')
    else:
        form = ArticleCreationForm()
    context = {'form' : form}
    return render(request, 'article/creation.html', context)


def delete_article(request):
    pass


def update_article(request):
    pass


def article_list(request):
    article = Article.objects.order_by('-publish_date')
    context = {
        'article':article
    }
    return render(request, 'article/view.html',context)


def detailed_article(request, title):
    detailed_article = Article.objects.get(title=title)
    comments = cModels.Comment.objects.filter(article=detailed_article)
    cform = cForms.CommentCreationForm()
    context = {
        'detailed_article': detailed_article,
        'comments': comments,
        'cform':cform

    }
    return render(request, 'article/detail.html', context)

comment/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from . forms import CommentCreationForm
import article.models as aModels

from django.contrib.auth.decorators import  login_required
# Create your views here.

@login_required(login_url='/account/login')
def create_comment(request):
    if request.method == 'GET':
            form = CommentCreationForm(request.GET)
            title = request.GET.get('title')
            article = aModels.Article.objects.get(title=title)
            comment = form.save(commit=False)
            comment.owner = request.user
            comment.article = article
            comment.save()
            url=reverse('article:detail', args=(title,))
            print(url)
            return HttpResponseRedirect(url)
    else:
        return redirect('home')

def update_comment(request):
    pass

def delete_comment(request):
    pass

article/templates/article/creation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Article Creation Page</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Create">
</form>
{% endblock %}

article/templates/article/detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}
{% block content %}
<div class="detail">
    <div class="title">
        Q: {{detailed_article.title|title}}
        <div class="otherDeatil">
        {{detailed_article.publish_date}}
        {{detailed_article.author}}
    </div>
    </div>
    <div class="description">
        Description: {{detailed_article.description}}
    </div>
    <h2>Comments</h2>
    <div class="comments">
        {% for comment in comments %}
        <div class="comment">
            {{comment.answer}}
            <div class="owner">
                {{comment.published_at}}
                {{comment.owner}}</div>
        </div>
    {% endfor %}
    </div>
    <form method="get" action="{% url 'comment:create' %}">
        {% csrf_token %}
        {{cform.as_p}}
        <input type="hidden" name="title" value="{{detailed_article.title}}">
        <input type="submit" value="CreateComment">
    </form>
</div>
{% endblock %}

article/templates/article/view.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/view.css' %}">
{% endblock %}

{% block content %}
<h1>Article List</h1>
<div class="articles">
{% for article in article %}
    <div class="article">
        <a href="{% url 'article:detail' article.title %}">{{article.title}}</a>
        <p class="author">created by {{article.author}}</p>
    </div>
{% endfor %}
</div>
{% endblock %}

templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>It's about Page</h1>
<h1>{{user}}</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
              {% load static %}
      {% block title %}{{title | default:'Learning'}}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
      {% block head %}

      {% endblock %}
  </head>
  <body>
    <div id="wrapper">
      <header id="header">
        <div id="logo">
          <img src="{% static 'images/logo.jpg' %}" alt="web_logo" width="30" height="30">
        </div>
        <div id="top_menu">
          <a href="{% url 'home' %}" class="btn">Home</a> | <a href="{% url 'about' %}" class="btn">About</a>
        </div>
        <br><div id="topbanner">
          <h1>DisQuession Forum</h1>
        </div>
        <div id="tab">
          <a href="{% url 'account:signup' %}"><button class="btn"><strong>SignUP</strong></button></a>
          {% if user.is_authenticated %}
            <a href="{% url 'account:logout' %}"><button class="btn"><strong>{{user.username}}</strong></button></a>
            <a href="{% url 'article:create' %}"><button class="btn"><strong>CreateArticle</strong></button></a>
          {% else %}
            <a href="{% url 'account:login' %}"><button class="btn"><strong>Login</strong></button></a>
          {% endif %}
      </div>
      </header>
      <aside id="rightside">
      </aside>
      <section id="main">
        {% block content %}
        {% endblock %}
      </section>
  <!--<script type="text/javascript">-->
  <!--window.onscroll = function() {myFunction()};-->
  <!--var header = document.getElementById("header");-->
  <!--var sticky = header.offsetTop;-->
  <!--function myFunction() {-->
    <!--if (window.pageYOffset > sticky) {-->
      <!--header.classList.add("sticky");-->
    <!--} else {-->
      <!--header.classList.remove("sticky");-->
    <!--}-->
  <!--}-->
  <!--</script>-->

  <script>
// Add active class to the current button (highlight it)
// var header = document.getElementById("tab")
var anchor = document.getElementsByTagName('a')
// btns = header.getElementsByClassName('btn')
var match_index = -1
$(function(){
  for(var j= 0; j<anchor.length; j++){
    if ((window.location.href) === (anchor[j]).href){
      match_index = j
    }
  }
  currentActive = document.getElementsByClassName('active')
  if(currentActive.length > 0){
    currentActive[0].classList.remove('active')
  }
  if (match_index != -1){
    anchor[match_index].getElementsByClassName('btn')[0].classList.add('active')
  }

})
</script>

  </script>
      <footer id="footer">@Copy Rights
        <script type="text/javascript">
          document.write(new Date().getFullYear());
        </script>
      </footer>
    </div>
  </body>
</html>